"""
Integration test for venue manager request notification flow.

Tests that when a player or director requests to become a venue manager,
the admin receives the appropriate notification.

Author: Venue Management Refactoring
Created: 2025-09-11
"""

import pytest
from models.base import db
from models.user.models import User, VenueManagerRequest
from models.user.venue_manager_service import VenueManagerService
import models.events  # noqa: F401 - Import to ensure handlers are registered
from models.notification.models import (
    Notification,
    NotificationType,
    NotificationPriority,
    NotificationStatus,
)
from models import BilliardHall
from models.location.services import LocationService


class TestVenueManagerNotifications:
    """Test suite for venue manager request notifications."""

    @pytest.fixture(autouse=True)
    def setup_test_data(self, app, client):
        """Set up test data for each test."""
        with app.app_context():
            # Clear existing notifications and requests
            Notification.query.delete()
            VenueManagerRequest.query.delete()

            # Create test venue
            self.test_venue = LocationService.create_billiard_hall(
                name="Test Venue Notifications",
                address="123 Test Street",
                city="Test City",
            )

            # Get test users
            admin = User.query.filter_by(role="admin").first()
            player = User.query.filter_by(role="player").first()
            director = User.query.filter_by(role="director").first()

            # Ensure we have required users
            if not admin:
                admin = User(
                    username="test_admin", email="admin@test.com", role="admin"
                )
                admin.set_password("password")
                db.session.add(admin)

            if not player:
                player = User(
                    username="test_player", email="player@test.com", role="player"
                )
                player.set_password("password")
                db.session.add(player)

            if not director:
                director = User(
                    username="test_director", email="director@test.com", role="director"
                )
                director.set_password("password")
                db.session.add(director)

            db.session.commit()

            # Store IDs to avoid detached instance errors
            self.admin_id = admin.id
            self.player_id = player.id
            self.director_id = director.id
            self.venue_id = self.test_venue.id

    def test_player_venue_manager_request_creates_admin_notification(self, app, client):
        """Test that a player's venue manager request creates notification for admin."""
        with app.app_context():
            # Get fresh objects from session
            admin = User.query.get(self.admin_id)
            player = User.query.get(self.player_id)
            venue = BilliardHall.query.get(self.venue_id)

            # Count initial notifications
            initial_admin_notifications = Notification.query.filter_by(
                user_id=admin.id
            ).count()

            # Player makes venue manager request
            request = VenueManagerService.create_venue_manager_request(
                user_id=player.id,
                venue_id=venue.id,
                notes="I would like to manage this venue",
            )

            # Verify request was created
            assert request is not None
            assert request.user_id == player.id
            assert request.venue_id == venue.id
            assert request.status == "pending"

            # Check that admin received notification
            admin_notifications = Notification.query.filter_by(
                user_id=admin.id, notification_type=NotificationType.SYSTEM_ANNOUNCEMENT
            ).all()

            # Should have one new notification
            assert len(admin_notifications) == initial_admin_notifications + 1

            # Get the new notification
            new_notification = admin_notifications[-1]

            # Verify notification content (generated by event handler)
            assert (
                new_notification.notification_type
                == NotificationType.SYSTEM_ANNOUNCEMENT
            )
            assert new_notification.status == NotificationStatus.PENDING
            # Event handler generates standardized title
            assert "Nuova Richiesta Gestore" in new_notification.title
            # Check venue name and player username in notification message
            assert "Test Venue Notifications" in new_notification.message
            assert player.username in new_notification.message
            assert (
                new_notification.priority == NotificationPriority.NORMAL
            )  # Non-contested

    def test_director_venue_manager_request_creates_admin_notification(
        self, app, client
    ):
        """Test that a director's venue manager request creates notification for admin."""
        with app.app_context():
            # Get fresh objects from session
            admin = User.query.get(self.admin_id)
            director = User.query.get(self.director_id)
            venue = BilliardHall.query.get(self.venue_id)

            # Count initial notifications
            initial_admin_notifications = Notification.query.filter_by(
                user_id=admin.id
            ).count()

            # Director makes venue manager request
            request = VenueManagerService.create_venue_manager_request(
                user_id=director.id,
                venue_id=venue.id,
                notes="As a director, I can help manage this venue",
            )

            # Verify request was created
            assert request is not None
            assert request.user_id == director.id
            assert request.venue_id == venue.id
            assert request.status == "pending"

            # Check that admin received notification
            admin_notifications = Notification.query.filter_by(
                user_id=admin.id,
                notification_type=NotificationType.SYSTEM_ANNOUNCEMENT,
            ).all()

            # Should have one new notification
            assert len(admin_notifications) == initial_admin_notifications + 1

            # Get the new notification
            new_notification = admin_notifications[-1]

            # Verify notification content (generated by event handler)
            assert (
                new_notification.notification_type
                == NotificationType.SYSTEM_ANNOUNCEMENT
            )
            assert new_notification.status == NotificationStatus.PENDING
            # Event handler generates standardized title
            assert "Nuova Richiesta Gestore" in new_notification.title
            # Check venue name and director username in notification message
            assert "Test Venue Notifications" in new_notification.message
            assert director.username in new_notification.message
            assert (
                new_notification.priority == NotificationPriority.NORMAL
            )  # Non-contested

    def test_contested_venue_request_has_high_priority(self, app, client):
        """Test that contested venue requests (venue already has manager) get HIGH priority."""
        with app.app_context():
            # Get fresh objects from session
            admin = User.query.get(self.admin_id)
            player = User.query.get(self.player_id)
            director = User.query.get(self.director_id)
            venue = BilliardHall.query.get(self.venue_id)

            # First, assign a manager to the venue
            from models.user.services import VenueManagementService

            # Create initial manager assignment
            VenueManagementService.assign_venue_manager(director.id, venue.id, admin)

            # Clear existing notifications after setup
            Notification.query.delete()
            db.session.commit()

            # Now player requests to manage same venue (contested)
            request = VenueManagerService.create_venue_manager_request(
                user_id=player.id,
                venue_id=venue.id,
                notes="I want to replace the current manager",
            )

            # Verify request is marked as contested
            assert request.is_contested == True

            # Check that admin received HIGH priority notification
            admin_notification = Notification.query.filter_by(
                user_id=admin.id,
                notification_type=NotificationType.SYSTEM_ANNOUNCEMENT,
            ).first()

            assert admin_notification is not None
            assert admin_notification.priority == NotificationPriority.HIGH  # Contested
            # Event handler generates standardized contested message
            assert "(CONTESA)" in admin_notification.title
            assert "ATTENZIONE" in admin_notification.message  # Warning message
            assert "contesa da altri gestori esistenti" in admin_notification.message

    def teardown_method(self):
        """Clean up after each test."""
        # Database cleanup is handled by test fixtures
        pass
